language: python
install: true
os: linux
dist: trusty
python:
  - "3.6"

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
script:
  - nosetests --exe --with-coverage --cover-xml --with-xunit

before_deploy: 
 - tar -czvf ./dist/battleship.tar.gz ./torpydo/
deploy: 
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 local_dir: dist

 on:
  branch: main